config/routes.rb
Rails.application.routes.draw do  
  get 'home/index'
  get 'welcome/index'
  get '/admin' => 'welcome#index'

  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
    resources :pages
    resources :menus
    get 'accesses' => 'accesses#index'
    post 'save_accesses' => 'accesses#create'
  end
  resources :items

  authenticated :user do
    root :to => 'home#index', as: :authenticated_root
    get '/admin' => 'home#index'
  end
  root :to => 'welcome#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
	has_many :accesses
	has_many :pages, through: :accesses
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    if @role.users.length == 0
      @assosciated_users = "None"
    else
      @assosciated_users = @role.users.map(&:name).join(", ")
    end    
    @accesses = Access.where(role_id: @role)
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create    
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        pages = params[:role][:pages]
        create_access(@role, pages)
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        pages = params[:role][:pages]
        create_access(@role, pages)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description, :admin, :manager)
    end

    # Cria o vinculo entre o perfil e as telas selecionadas, deleta anteriores
    def create_access(role, pages)
      role.accesses.destroy_all
      pages.each do |p|
        if !p.empty?
          role.accesses.create({role_id: role, page_id: p.to_i})
        end
      end
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role, html: {class: "form-horizontal"}) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@role.errors.count, "error") %> prohibited this role from 
        being saved:
      </h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-offset-3 col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, autofocus: true, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-offset-3 col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_area :description, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-4">
      <%= f.check_box :admin %>
      <%= f.label :admin, 'Administrator' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-4">
      <%= f.check_box :manager %>
      <%= f.label :manager, 'Manager' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :pages, "Pages", 
                              class: "col-sm-offset-2 col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= collection_select(:role, :pages, Page.all, :id, :name, 
            {selected: @role.page_ids, include_blank: false, prompt: false}, 
            multiple: true, class: "form-control input-sm")  %>                             
    </div>                                                              
  </div>

  <div class="form-group">
    <div class="row well well-sm">
      <%= f.submit "Save", class: btn_create("col-sm-offset-4") %>
      <%= button_tag link_icon("trash", "Clear"), type: :reset, 
                                      class: btn_show %>                                 
    </div>
  </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#role_pages').multiselect({
      maxHeight: 200,
      enableFiltering: true,
      nonSelectedText: 'Select the pages',
      includeSelectAllOption: true,
      allSelectedText: 'All selected'
    });
  });
</script>

app/views/roles/edit.html.erb
<%= provide(:title, "Editing #{@role.name}") %>
<%= render 'form' %>

<div class="row row-margin">
	<%= link_to link_icon('arrow-left', 'Back'), roles_path, 
																								class: btn_show('left') %>
	<%= link_to link_icon('user', 'Show'), @role, class: btn_show('right') %>
</div>

app/views/roles/index.html.erb
<%= provide(:title, 'Roles') %>
<p id="notice"><%= notice %></p>

<div class="row row-margin">
  <div class="col-sm-12">
    <table class="table table-hover table-striped table-resposive">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="2" width="10%"></th>
        </tr>
      </thead>
      <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td><%= link_to role.name, role %></td>
            <td><%= role.description %></td>          
            <td>
              <%= link_to link_icon('edit'), edit_role_path(role), 
                                        class: btn_edit %>
            </td>
            <td>
              <%= link_to link_icon('remove'), role, method: :delete, 
                                        data: { confirm: 'Are you sure?' },
                                        class: btn_destroy %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row row-margin">
  <div class="col-sm-12">
    <% if can? :manage, Role %>
      <%= link_to link_icon('plus', 'New Role'), new_role_path, 
                                                              class: btn_create %>
    <% end %>
  </div>
</div>

app/views/roles/new.html.erb
<%= provide(:title, 'New Role') %>

<%= render 'form' %>

<div class="row row-margin">
	<%= link_to link_icon('arrow-left', 'Back'), roles_path, class: btn_show %>
</div>

app/views/roles/show.html.erb
<%= provide(:title, @role.name) %>

<p id="notice"><%= notice %></p>

<div class="row content_info">
  <div class="row">
    <strong>Name:</strong>
    <%= @role.name %>
  </div>

  <div class="row">
    <strong>Description:</strong>
    <%= @role.description %>
  </div>

  <div class="row">
    <strong>Assosciated users:</strong>
    <%= @assosciated_users %>
  </div>

  <% if @role.admin? %>
    <div class="row">
      Can manage everything
    </div>
  <% elsif @role.manager? %>
    <div class="row">
      Can manage some stuff
    </div>
  <% else %>
    <div class="row">
      Doesn't have any privileges
    </div>
  <% end %>
</div>

<div class="row row-margin">
  <div class="col-sm-10">
    <table class="table table-bordered table-striped table-resposive">
      <thead>
        <tr>
          <th>Name</th>
          <th>Path</th>
          <th width="5%">Create</th>
          <th width="5%">Read</th>
          <th width="5%">Update</th>
          <th width="5%">Destroy</th>
        </tr>
      </thead>

      <tbody>
        <% @accesses.each do |access| %>
          <%= content_tag_for(:tr, access) do |acc| %>
            <td><%= link_to acc.page.name, acc.page %></td>
            <td><%= acc.page.path %></td>
            <td align="center">
              <%= render_checkbox "create",  acc.can_create  %>
            </td>
            <td align="center">
              <%= render_checkbox "read",    acc.can_read    %>
            </td>
            <td align="center">
              <%= render_checkbox "update",  acc.can_update  %>
            </td>
            <td align="center">
              <%= render_checkbox "destroy", acc.can_destroy %>
            </td>
          <% end %>
        <% end %>
      </tbody>
    </table>      
  </div>
</div>

<div class="row row-margin">
  <%= link_to link_icon('arrow-left', 'Back'), roles_path, 
                                                	class: btn_show('left')  %>
  <% if can? :manage, Access %>
    <%= link_to link_icon('check', 'Manage Access'), accesses_path, 
                                                  class: btn_show('right') %>
  <% end %>
  <%= link_to link_icon('edit', 'Edit'), edit_role_path(@role), 
                                                  class: btn_edit('right') %>
</div>