config/routes.rb
Rails.application.routes.draw do  
  get 'home/index'
  get 'welcome/index'
  get '/admin' => 'welcome#index'

  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
    resources :pages
    resources :menus
    get 'accesses' => 'accesses#index'
    post 'save_accesses' => 'accesses#create'
  end
  resources :items

  authenticated :user do
    root :to => 'home#index', as: :authenticated_root
    get '/admin' => 'home#index'
  end
  root :to => 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: {class: "form-horizontal"}) do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-offset-1 col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, autofocus: true, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-offset-1 col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :description, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-sm-offset-1 col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.number_field :price, class: "form-control input-sm", 
                                  :step => 'any' %>
    </div>
  </div>

  <div class="form-group">
    <div class="row well well-sm">
      <%= f.submit "Save", class: btn_create("col-sm-offset-3") %>
      <%= button_tag link_icon("trash", "Clear"), type: :reset, 
                                      class: btn_show %>
    </div>
  </div>  

<% end %>

app/views/items/_list.html.erb
<div class="row row-margin">
  <ul class="items-list">
    <% @items.each do |item| %>
      <li>      
        <div class="row">
          <div class="col-sm-12">
            <h4><strong><%= link_to item.name, item %></strong></h4>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-10">
            <strong>Seller:</strong> <%= item.user.name %>
          </div>
          <div class="col-sm-2">
            <strong>Price:</strong> <%= item.price %>
          </div>
        </div>
        
        <div class="row">
          <div class="col-sm-12">
            <strong>Description:</strong> <%= item.description %>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <% if can? :update, item %>
              <%= link_to link_icon('edit', 'Edit'), edit_item_path(item), class: btn_edit %>            
            <% end %>
            <% if can? :destroy, item %>            
              <%= link_to link_icon('remove', 'Destroy'), item, method: :delete, 
                                    data: { confirm: 'Are you sure?' }, class: btn_destroy %>            
            <% end %>
          </div>          
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/items/_table.html.erb
<div class="row row-margin">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Seller</th>
        <th colspan="2" width="10%"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item %></td>
          <td><%= item.description %></td>
          <td><%= item.price %></td>
          <td><%= item.user.name %></td>          
          <% if can? :update, item %>
            <td>
              <%= link_to link_icon('edit', ''), edit_item_path(item), 
                                                  class: btn_edit %>
            </td>
          <% end %>
          <% if can? :destroy, item %>
            <td>
              <%= link_to link_icon('remove', ''), item, method: :delete, 
                                            data: { confirm: 'Are you sure?' },
                                            class: btn_destroy %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/backup.html.erb
<%= provide(:title, 'Items') %>

<div class="col-sm-12">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Seller</th>
        <th colspan="2" width="10%"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item %></td>
          <td><%= item.description %></td>
          <td><%= item.price %></td>
          <td><%= item.user.name %></td>          
          <% if can? :update, item %>
            <td>
              <%= link_to link_icon('edit', ''), edit_item_path(item), 
                                                  class: btn_edit %>
            </td>
          <% end %>
          <% if can? :destroy, item %>
            <td>
              <%= link_to link_icon('remove', ''), item, method: :delete, 
                                            data: { confirm: 'Are you sure?' },
                                            class: btn_destroy %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if can? :create, Item %>
  <%= link_to link_icon('plus', 'New Item'), new_item_path, class: btn_create %>
<% end %>

app/views/items/edit.html.erb
<%= provide(:title, "Editing #{@item.name}") %>

<%= render 'form' %>

<div class="row row-margin">
	<%= link_to link_icon('arrow-left', 'Back'), items_path, 
												class: btn_show('left') %>
	<%= link_to link_icon('gift', 'Show'), @item, 
												class: btn_show('right') %>
</div>

app/views/items/index.html.erb
<%= provide(:title, 'Items') %>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#list" aria-controls="list" role="tab" data-toggle="tab">
        <%= link_icon('list', 'List') %>
      </a>
    </li>
    <li role="presentation">
      <a href="#table" aria-controls="table" role="tab" data-toggle="tab">
        <%= link_icon('list-alt', 'Table') %>
      </a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="list"><%= render 'list' %></div>
    <div role="tabpanel" class="tab-pane" id="table"><%= render 'table' %></div>    
  </div>

</div>

<% if can? :create, Item %>
  <%= link_to link_icon('plus', 'New Item'), new_item_path, class: btn_create %>
<% end %>

app/views/items/new.html.erb
<%= provide(:title, 'New Item') %>

<%= render 'form' %>

<div class="row row-margin">
	<%= link_to link_icon('arrow-left', 'Back'), items_path, class: btn_show %>
</div>

app/views/items/show.html.erb
<%= provide(:title, @item.name) %>

<div class="row content_info">

  <div class="row">
    <strong>Description:</strong>
    <%= @item.description %>
  </div>

  <div class="row">
    <strong>Price:</strong>
    <%= @item.price %>
  </div>

  <div class="row">
    <strong>Seller:</strong>
    <%= link_to @item.user.name, @item.user %>
  </div>
  
</div>

<div class="row row-margin">
  <%= link_to link_icon('arrow-left', 'Back'), items_path, 
                                                class: btn_show('left') %>
  <% if can? :update, @item %>
    <%= link_to link_icon('edit', 'Edit'), edit_item_path(@item), 
                                                  class: btn_edit('right') %>
  <% end %>
  <% if can? :destroy, @item %>
    <%= link_to link_icon('remove', 'Destroy'), @item, method: :delete, 
                                            data: { confirm: 'Are you sure?' },
                                            class: btn_destroy('right') %>
  <% end %>
</div>