config/routes.rb
Rails.application.routes.draw do  
  get 'home/index'
  get 'welcome/index'
  get '/admin' => 'welcome#index'

  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
    resources :pages
    resources :menus
    get 'accesses' => 'accesses#index'
    post 'save_accesses' => 'accesses#create'
  end
  resources :items

  authenticated :user do
    root :to => 'home#index', as: :authenticated_root
    get '/admin' => 'home#index'
  end
  root :to => 'welcome#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" 
							data-toggle="collapse" data-target="#navbar" 
							aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if !user_signed_in? %>
      <% end %>
      <strong>
        <%= link_to 'Store', root_path, class: "navbar-brand" %>
      </strong>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <!-- <li>
          <% #if user_signed_in? %>
            <% #link_to link_icon('home', 'Home'), authenticated_root_path %>
          <% #end %>
      	</li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                      role="button" aria-haspopup="true" aria-expanded="false">
    						<strong>
    							<%= link_icon('cog', 'Settings') %> 
    							<span class="caret"></span>
  							</strong>
						</a>
            <ul class="dropdown-menu">
              <li>
              	<%= link_to "Profile", current_user %>
            	</li>
              <% if (can? :manage, User) || (can? :manage, Role) %>
                <li class="dropdown-header">Management</li>
              <% end %>
              <% if can? :manage, User %>
                <li><%= link_to "Users", users_path %></li>
              <% end %>
              <% if can? :manage, Role %>
              	<li><%= link_to "Roles", roles_path %></li>
              <% end %>
							<li role="separator" class="divider"></li>
							<li>
						  	<%= link_to link_icon('log-out', "Sign out"), destroy_user_session_path, 
			  																							:method => :delete %>
						  </li>
            </ul>
          </li>
				<% else %>
          <%= render 'devise/sessions/panel' %>
				<% end %>            
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>	

app/views/layouts/_sidebar.html.erb
<div class="nav-side-menu">
  <div class="brand">
    <div class="row row-margin">
      <div class="col-sm-12">
        <div class="col-sm-3 user-identification">
          <%= link_to gravatar_for( current_user, size: "50"), current_user %>
        </div>
        <div class="col-sm-9 user-identification" style="margin: 0; padding: 0;">        
          <%= sidebar_link('', 
              "#{current_user.first_name} | #{current_user.role.name}".html_safe, 
                                    path = current_user) %>          
        </div>
      </div>
    </div>
  </div>
  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" 
    data-target="#menu-content"></i>  
  <div class="menu-list">
    <ul id="menu-content" class="menu-content collapse out">          

      <%= user_navigation %>      
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 
	  														'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag 'favicon.ico' %>
	</head>
	<body>
  	<% if user_signed_in? %>
			<div class="side">
				<%= render 'layouts/sidebar' %>
			</div>
			<div class="authenticated">
	    	<%= render 'layouts/header' %>
	    	
				<div class="container">
					<div class="content">	

						<% flash.each do |type, message| %>
							<div class="alert alert-info">
								<button type="button" class="close" 
									data-dismiss="alert" aria-hidden="true">&times;</button>
					      <%= content_tag(:div, message) %>
							</div>
			    	<% end %> 

						<div class="page-header">			    	
							<strong><h3><%= yield(:title) %></h3></strong>
						</div>

						<%= yield %>
					</div>
				</div>
			</div>
		<% else %>	
			<div class="non_authenticated">  		
				<%= render 'layouts/header' %>

				<div class="container">	
					<div class="content">
						<% flash.each do |type, message| %>
							<div class="alert alert-info">
								<button type="button" class="close" 
									data-dismiss="alert" aria-hidden="true">&times;</button>
					      <%= content_tag(:div, message) %>
							</div>
			    	<% end %> 

						<div class="page-header">			    	
							<strong><h3><%= yield(:title) %></h3></strong>
						</div>
						<%= yield %>
					</div>
				</div>
			</div>
		<% end %>	

	</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 
	  														'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag 'favicon.ico' %>
	</head>
	<body>
  	<!-- if user_signed_in? -->
		<div class="side">
			<%= render 'layouts/sidebar' %>
		</div>
		<div class="authenticated">
    	<%= render 'layouts/header' %>
    	
			<div class="container">
				<div class="content">	

					<%= render 'shared/alert' %>

					<div class="page-header">			    	
						<strong><h3><%= yield(:title) %></h3></strong>
					</div>

					<%= yield %>
				</div>
			</div>
			<div class="debug">
				<%= debug(params) if Rails.env.development? %>
			</div>
		</div>
	</body>
</html>

app/views/layouts/visitor.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 
	  														'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= favicon_link_tag 'favicon.ico' %>
	</head>
	<body>
		<div class="non_authenticated">  		
			<%= render 'layouts/header' %>
			
			<div class="container">	
				<div class="content">
				
					<%= render 'shared/alert' %>

					<div class="page-header">			    	
						<strong><h3><%= yield(:title) %></h3></strong>
					</div>
					<%= yield %>
				</div>
			</div>
		</div>
	</body>
</html>